services:
  postgres:
    image: postgres
    container_name: postgres-carrier
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
    ports:
      - "5434:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "9003:8080"